force-app/main/default/objects/Labor_Exchange_Community_Setup__c/Labor_Exchange_Community_Setup__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Labor Exchange Community Setup</label>
</CustomObject>

force-app/main/default/objects/Labor_Exchange_Community_Setup__c/fields/ContactRecordTypes__c.field-meta.xml
<CustomField>
    <fullName>ContactRecordTypes__c</fullName>
    <description>Determines which Contacts to include in Candidate Search</description>
    <inlineHelpText>Please provide a comma-separated list. Record Types listed are queried in the Candidate Search for the LEX Community. They must also be have a Launchpad__Stage__c picklist value that meets one listed in the Searchable Contact Stages custom setting field.</inlineHelpText>
    <label>Contact Record Type Dev Names</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Labor_Exchange_Community_Setup__c/fields/Eligible_Open_Job_Stages__c.field-meta.xml
<CustomField>
    <fullName>Eligible_Open_Job_Stages__c</fullName>
    <description>Determines which Job Stages qualify as &quot;Open Jobs&quot;.</description>
    <inlineHelpText>Please provide a comma-separated list. Job stages listed here will be used when &quot;Open Jobs&quot; are displayed within the Labor Exchange community.</inlineHelpText>
    <label>Eligible Open Job Stages</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Labor_Exchange_Community_Setup__c/fields/Events_Page_URL__c.field-meta.xml
<CustomField>
    <fullName>Events_Page_URL__c</fullName>
    <inlineHelpText>Enables events page to be accessed from outside the community.</inlineHelpText>
    <label>Events Page URL</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Labor_Exchange_Community_Setup__c/fields/Jobs_Page_URL__c.field-meta.xml
<CustomField>
    <fullName>Jobs_Page_URL__c</fullName>
    <inlineHelpText>Enables jobs page to be accessed from outside the community.</inlineHelpText>
    <label>Jobs Page URL</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Labor_Exchange_Community_Setup__c/fields/LEX_Community_Permission_Set_Id__c.field-meta.xml
<CustomField>
    <fullName>LEX_Community_Permission_Set_Id__c</fullName>
    <label>LEX Community Permission Set Id</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Labor_Exchange_Community_Setup__c/fields/LEX_Community_Profile_Id__c.field-meta.xml
<CustomField>
    <fullName>LEX_Community_Profile_Id__c</fullName>
    <label>LEX Community Profile Id</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Labor_Exchange_Community_Setup__c/fields/of_Tiles_Per_Page__c.field-meta.xml
<CustomField>
    <fullName>of_Tiles_Per_Page__c</fullName>
    <defaultValue>6</defaultValue>
    <inlineHelpText>Controls how many Tiles will display on a Page before Pagination.  This applies to Home Page Tiles, Event Tiles and Job Tiles.</inlineHelpText>
    <label># of Tiles Per Page</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/LEXMatchesToMyJobsControllerTest.cls
@isTest
private without sharing class LEXMatchesToMyJobsControllerTest {
	@TestSetup
	static void makeData() {
		User adminUser = [SELECT Id, UserRoleId FROM User WHERE Id = :UserInfo.getUserId() LIMIT 1];
		UserRole ownerRole = new UserRole(Name = 'Owner Role');
		insert ownerRole;

		adminUser.UserRoleId = ownerRole.Id;
		update adminUser;

		System.runAs(adminUser) {
			Labor_Exchange_Community_Setup__c lexCommunitySetup = new Labor_Exchange_Community_Setup__c(
				Events_Page_URL__c = 'www.google.com',
				Jobs_Page_URL__c = 'www.google.com',
				of_Tiles_Per_Page__c = 6,
				ContactRecordTypes__c = 'Employer',
				Eligible_Open_Job_Stages__c = 'Open',
				LEX_Community_Profile_Id__c = [SELECT Id FROM Profile WHERE Name = 'Customer Community User' LIMIT 1][0]
				.Id,
				LEX_Community_Permission_Set_Id__c = [SELECT Id FROM PermissionSet WHERE Name = 'Labor_Exchange_User_Permissions' LIMIT 1][0]
				.Id
			);
			insert lexCommunitySetup;

			Account account = (Account) new SObjectBuilder(Account.sObjectType)
				.put(Account.Name, 'Test Com Account')
				.put(Account.RecordTypeId, Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Employer').getRecordTypeId())
				.put(Account.OwnerId, getAdminUser().Id)
				.create()
				.getRecord();

			Contact contact = (Contact) new SObjectBuilder(Contact.sObjectType)
				.put(Contact.AccountId, account.Id)
				.put(Contact.FirstName, 'Test')
				.put(Contact.LastName, 'Contact')
				.put(Contact.Launchpad__Created_via_Community_Self_Registration__c, true)
				.put(Contact.RecordTypeId, Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Employer').getRecordTypeId())
				.create()
				.getRecord();

			new SObjectBuilder(User.sObjectType)
				.put(User.FirstName, 'Privileged')
				.put(User.LastName, 'User')
				// .put(User.ProfileId, [SELECT Id FROM Profile WHERE Name = 'Labor Exchange Community User'][0].Id)
				.put(User.ProfileId, [SELECT Id FROM Profile WHERE Name = 'Customer Community User' LIMIT 1][0].Id)
				.put(User.ContactId, contact.Id)
				.create()
				.getRecord();

			new SObjectBuilder(Launchpad__Job__c.sObjectType)
				.put(Launchpad__Job__c.Launchpad__Stage__c, 'Open')
				.put(Launchpad__Job__c.Launchpad__Account__c, account.Id)
				.create();

			new SObjectBuilder(Launchpad__Job__c.sObjectType)
				.put(Launchpad__Job__c.Launchpad__Stage__c, 'Offered')
				.put(Launchpad__Job__c.Launchpad__Account__c, account.Id)
				.create();
		}
	}

	// @isTest
	// private static void getJobData() {
	// 	User communityUser = [SELECT Id FROM User WHERE firstName = 'Privileged' LIMIT 1];

	// 	System.runAs(communityUser) {
	// 		Test.startTest();
	// 		List<Launchpad__Job__C> jobs = LEXMatchesToMyJobsController.getJobData();
	// 		Test.stopTest();

	// 		Assert.areEqual(1, jobs.size(), 'No jobs returned');
	// 	}
	// }

	@isTest
	private static void getJobDataNoContact() {
		User user = (User) new SObjectBuilder(User.sObjectType)
			.put(User.CommunityNickname, 'standarduser' + DateTime.now().getTime())
			.put(User.Username, 'standarduser' + DateTime.now().getTime() + '@' + Math.random() + '.com')
			.create()
			.getRecord();

		System.runAs(user) {
			Exception thrownException;

			try {
				Test.startTest();
				List<Launchpad__Job__c> jobs = LEXMatchesToMyJobsController.getJobData();
				Test.stopTest();
			} catch (Exception ex) {
				thrownException = ex;
			}

			Assert.isNotNull(thrownException, 'No exception thrown');
		}
	}

	@isTest
	private static void getJobMatchesAll() {
		User communityUser = [SELECT Id FROM User WHERE firstName = 'Privileged' LIMIT 1];

		System.runAs(communityUser) {
			String jobFilter = 'All';

			LEXMatchesToMyJobsController.MatchFieldSet matchFieldSet;

			Test.startTest();
			matchFieldSet = LEXMatchesToMyJobsController.getJobMatches(jobFilter);
			Test.stopTest();

			Assert.isNotNull(matchFieldSet, 'No matches');
		}
	}

	@isTest
	private static void getJobMatchesNoContact() {
		User user = (User) new SObjectBuilder(User.sObjectType)
			.put(User.CommunityNickname, 'standarduser' + DateTime.now().getTime())
			.put(User.Username, 'standarduser' + DateTime.now().getTime() + '@' + Math.random() + '.com')
			.create()
			.getRecord();

		System.runAs(user) {
			String jobFilter = 'All';
			Exception thrownException;

			try {
				Test.startTest();
				LEXMatchesToMyJobsController.MatchFieldSet matchFieldSet = LEXMatchesToMyJobsController.getJobMatches(jobFilter);
				Test.stopTest();
			} catch (Exception ex) {
				thrownException = ex;
			}

			Assert.isNotNull(thrownException, 'An error was not thrown');
		}
	}

	private static User getAdminUser() {
		return [SELECT Id FROM User WHERE Profile.Name = 'System Administrator' AND UserRoleId != NULL LIMIT 1];
	}
}