force-app/main/default/objects/LaborExchangeCommunity_FieldProperties__mdt/LaborExchangeCommunity_FieldProperties__mdt.object-meta.xml
<CustomObject>
    <label>LaborExchangeCommunity_FieldProperties</label>
    <pluralLabel>LaborExchangeCommunity_FieldProperties</pluralLabel>
</CustomObject>

force-app/main/default/objects/LaborExchangeCommunity_FieldProperties__mdt/fields/Custom_Help_Text__c.field-meta.xml
<CustomField>
    <fullName>Custom_Help_Text__c</fullName>
    <inlineHelpText>Help Text for the Field.</inlineHelpText>
    <label>Custom Help Text</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/LaborExchangeCommunity_FieldProperties__mdt/fields/Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Field_API_Name__c</fullName>
    <inlineHelpText>API Name for the Field.</inlineHelpText>
    <label>Field API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LaborExchangeCommunity_FieldProperties__mdt/fields/Field_Label__c.field-meta.xml
<CustomField>
    <fullName>Field_Label__c</fullName>
    <inlineHelpText>Controls the field label should be displayed as within the Community.</inlineHelpText>
    <label>Field Label</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/LaborExchangeCommunity_FieldProperties__mdt/fields/Field_Screen_Size__c.field-meta.xml
<CustomField>
    <fullName>Field_Screen_Size__c</fullName>
    <inlineHelpText>Controls the number of fields displayed per line. There are 12 “spaces” per line. If you want one field in a line, set the screen size to 12. Two fields = 6, Three fields = 4, and 4 fields = 3.</inlineHelpText>
    <label>Field Screen Size</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>2</fullName>
                <default>true</default>
                <label>2</label>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/LaborExchangeCommunity_FieldProperties__mdt/fields/LaborExchangeCommunity_PageProperties__c.field-meta.xml
<CustomField>
    <fullName>LaborExchangeCommunity_PageProperties__c</fullName>
    <inlineHelpText>Controls which Custom Metadata Property Page the Field Properties should be applied to.</inlineHelpText>
    <label>LaborExchangeCommunity_PageProperties</label>
    <referenceTo>LaborExchangeCommunity_PageProperties__mdt</referenceTo>
    <relationshipLabel>LaborExchangeCommunity_FieldProperties</relationshipLabel>
    <relationshipName>LaborExchangeCommunity_FieldProperties</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/LaborExchangeCommunity_FieldProperties__mdt/fields/Override_Setup_Help_Text__c.field-meta.xml
<CustomField>
    <fullName>Override_Setup_Help_Text__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>This allows clients the ability to override the field’s existing help text information only for job seeker community. If left unchecked, it will default to whatever help text is set up for the field across the org,</inlineHelpText>
    <label>Override Setup Help Text</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/LaborExchangeCommunity_FieldProperties__mdt/fields/Read_Only__c.field-meta.xml
<CustomField>
    <fullName>Read_Only__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Controls if the field is informational only.</inlineHelpText>
    <label>Read Only</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/LaborExchangeCommunity_PageProperties__mdt/LaborExchangeCommunity_PageProperties__mdt.object-meta.xml
<CustomObject>
    <label>LaborExchangeCommunity_PageProperties</label>
    <pluralLabel>LaborExchangeCommunity_PageProperties</pluralLabel>
</CustomObject>

force-app/main/default/objects/LaborExchangeCommunity_PageProperties__mdt/fields/Field_Set__c.field-meta.xml
<CustomField>
    <fullName>Field_Set__c</fullName>
    <inlineHelpText>Controls the Field Set that defines the Fields that will display and whether or not they are required.</inlineHelpText>
    <label>Field Set</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LaborExchangeCommunity_PageProperties__mdt/fields/Section_Order__c.field-meta.xml
<CustomField>
    <fullName>Section_Order__c</fullName>
    <inlineHelpText>Controls the Order the Section should appear.</inlineHelpText>
    <label>Section Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LaborExchangeCommunity_PageProperties__mdt/fields/Sub_Header__c.field-meta.xml
<CustomField>
    <fullName>Sub_Header__c</fullName>
    <inlineHelpText>Controls the Text that is displayed in the Sub Header for the Section.</inlineHelpText>
    <label>Sub Header</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/LEXEditContactModalController.cls
/*****************************************************************************
 * @CLASS NAME     : LEXEDITCONTACTMODALCONTROLLER                           *
 * @CLASS PURPOSE  : HANDLES THE LOGIC BEHIND THE LEXEDITCONTACTMODAL LWC    *
 * @DEVELOPER      : RADIANHUB DEVELOPER                                     *
 * @DEVELOPED ON   : 04/07/2023                                              *
 *****************************************************************************/
public without sharing class LEXEditContactModalController {
	public class MyContactData {
		@AuraEnabled
		public List<Section> sections;

		@AuraEnabled
		public Contact myContact;
	}

	public class Section {
		@AuraEnabled
		public String id;

		@AuraEnabled
		public String header;

		@AuraEnabled
		public String subHeader;

		@AuraEnabled
		public String fieldSetName;

		@AuraEnabled
		public List<Field> fields;

		public Section(String id, String header, String subHeader, String fieldSetName, Integer sortOrder) {
			this.id = id;
			this.header = header;
			this.subHeader = subHeader;
			this.fieldSetName = fieldSetName;
			this.fields = new List<Field>();
		}
	}

	public class Field {
		@AuraEnabled
		public String fieldName;

		@AuraEnabled
		public String fieldLabel;

		@AuraEnabled
		public String helpText;

		@AuraEnabled
		public String screenSize;

		@AuraEnabled
		public String type;

		@AuraEnabled
		public Boolean isReadOnly;

		@AuraEnabled
		public Boolean isDisabled;

		@AuraEnabled
		public Boolean isRequired;

		@AuraEnabled
		public String min;

		@AuraEnabled
		public string max;

		@AuraEnabled
		public String minMsg;

		@AuraEnabled
		public string maxMsg;

		@AuraEnabled
		public Boolean isText;

		@AuraEnabled
		public Boolean isEmail;

		@AuraEnabled
		public Boolean isDate;

		@AuraEnabled
		public Boolean isCheckbox;

		@AuraEnabled
		public Boolean isNumber;

		@AuraEnabled
		public Boolean isPhone;

		@AuraEnabled
		public Boolean isTextarea;

		@AuraEnabled
		public Boolean isPicklist;

		@AuraEnabled
		public Boolean isMultiPicklist;

		@AuraEnabled
		public Boolean isUrl;

		@AuraEnabled
		public List<LEXCommunityHelper.Option> values;

		public Field(String fieldName, String fieldLabel, String helpText, String screenSize, String type, Boolean isReadOnly, Boolean isRequired) {
			this.fieldName = fieldName;
			this.fieldLabel = fieldLabel;
			this.helpText = helpText;
			this.screenSize = screenSize;
			this.isReadOnly = isReadOnly;
			this.isDisabled = true;
			this.isRequired = isRequired;
			this.isText = type == 'STRING';
			this.isEmail = type == 'EMAIL';
			this.isDate = type == 'DATE' || type == 'DATETIME';
			this.isCheckbox = type == 'BOOLEAN';
			this.isNumber = type == 'CURRENCY' || type == 'PERCENT' || type == 'DOUBLE';
			this.isPhone = type == 'PHONE';
			this.isTextarea = type == 'TEXTAREA';
			this.isPicklist = type == 'PICKLIST';
			this.isMultiPicklist = type == 'MULTIPICKLIST';
			this.isUrl = type == 'URL';
			this.type = type == 'DOUBLE' ? 'decimal' : type.toLowerCase();
		}
	}

	/*****************************************************************************************
	 * @DESCRIPTION : QUERY METADATA FOR FIELD SETS AND RETURN THE FIELDS WITH CONTACT DATA. *
	 * @AUTHOR RADIANHUB DEVELOPER | 04/07/2023                                              *
	 * @RETURN MYCONTACTDATA                                                                 *
	 *****************************************************************************************/
	@AuraEnabled(cacheable=true)
	public static MyContactData fetchContactData(String contactId) {
		try {
			MyContactData data = new MyContactData();
			data.sections = new List<Section>();

			Set<Id> pageSectionIds = new Set<Id>();
			Set<String> fieldSet = new Set<String>();
			Map<String, LaborExchangeCommunity_FieldProperties__mdt> fieldsMap = new Map<String, LaborExchangeCommunity_FieldProperties__mdt>();

			List<LaborExchangeCommunity_PageProperties__mdt> ppList = LEXCommunityHelper.getLEXPageProperties('Company Profile > Edit/New Contact Popup');
			for (LaborExchangeCommunity_PageProperties__mdt pp : ppList) {
				data.sections.add(new Section(pp.Id, pp.Section_Header__c, pp.Sub_Header__c, pp.Field_Set__c, Integer.valueOf(pp.Section_Order__c)));
				pageSectionIds.add(pp.Id);
			}

			List<LaborExchangeCommunity_FieldProperties__mdt> fpList = LEXCommunityHelper.getLEXFieldProperties(pageSectionIds);
			for (LaborExchangeCommunity_FieldProperties__mdt fp : fpList) {
				fieldsMap.put(fp.LaborExchangeCommunity_PageProperties__c + '-' + fp.Field_API_Name__c, fp);
			}

			Schema.DescribeSObjectResult dor = LEXCommunityHelper.getSObjSchema('Contact');

			for (Section s : data.sections) {
        Schema.FieldSet objectFieldSet = LEXCommunityHelper.getFieldSet('Contact', s.fieldSetName);

				if (objectFieldSet == null) {
					continue;
				}

				for (Schema.FieldSetMember fm : objectFieldSet.getFields()) {					LaborExchangeCommunity_FieldProperties__mdt fp = fieldsMap.containsKey(s.Id + '-' + fm.getFieldPath())
						? fieldsMap.get(s.Id + '-' + fm.getFieldPath())
						: null;

					fieldSet.add(fm.getFieldPath());
					Field f = new Field(
						fm.getFieldPath(),
						fp != null && fp.Field_Label__c != null ? fp.Field_Label__c : fm.getLabel(),
						fp != null && fp.Override_Setup_Help_Text__c ? fp.Custom_Help_Text__c : null,
						fp != null && fp.Field_Screen_Size__c != null ? fp.Field_Screen_Size__c : '6',
						String.valueOf(fm.getType()),
						fp != null && fp.Read_Only__c,
						fm.getRequired()
					);

					if (String.valueOf(fm.getType()) == 'PICKLIST' || String.valueOf(fm.getType()) == 'MULTIPICKLIST') {
						Schema.DescribeFieldResult fr = dor.fields.getMap().get(fm.getFieldPath()).getDescribe();
						f.values = new List<LEXCommunityHelper.Option>(LEXCommunityHelper.getPicklistValues(fr));
					}

					s.fields.add(f);
				}
			}

			List<String> fieldList = new List<String>(fieldSet);

			String query = 'SELECT Id';

			if (fieldList.size() > 0) {
				query += ', {0} FROM Contact WHERE Id = :contactId WITH SECURITY_ENFORCED';
				query = String.format(query, new List<String>{ String.join(fieldList, ',') });
			} else {
				query += ' FROM Contact WHERE Id = :contactId WITH SECURITY_ENFORCED';
			}

			List<Contact> contactList = Database.query(query);
			if (contactList.size() > 0) {
				data.myContact = contactList[0];
			}
			return data;
		} catch (Exception e) {
			System.debug('Exception: ' + e.getMessage() + ' @ ' + e.getStackTraceString());
			throw new AuraHandledException(e.getMessage());
		}
	}

	/*********************************************
	 * @DESCRIPTION : UPDATE A GIVEN CONTACT     *
	 * @AUTHOR RADIANHUB DEVELOPER | 04/07/2023  *
	 * @RETURN Boolean                           *
	 *********************************************/
	@AuraEnabled
	public static Boolean upsertContact(String conString) {
		try {
			Contact con = (Contact) JSON.deserialize(conString, Contact.class);
			// ! User needs system context to Assign a New Contact Owner.
			Database.UpsertResult[] urList = Database.upsert(new List<Contact>{ con });
			for (Database.UpsertResult ur : urList) {
				if (ur.isSuccess()) {
					return true;
				} else {
					for (Database.Error err : ur.getErrors()) {
						throw new CustomException(err.getStatusCode() + ': ' + err.getMessage());
					}
				}
			}
			return true;
		} catch (Exception e) {
			System.debug('Exception: ' + e.getMessage() + ' @ ' + e.getStackTraceString());
			throw new AuraHandledException(e.getMessage());
		}
	}

	public class CustomException extends Exception {
	}
}