force-app/main/default/objects/LaborExchangeCommunity_FieldProperties__mdt/LaborExchangeCommunity_FieldProperties__mdt.object-meta.xml
<CustomObject>
    <label>LaborExchangeCommunity_FieldProperties</label>
    <pluralLabel>LaborExchangeCommunity_FieldProperties</pluralLabel>
</CustomObject>

force-app/main/default/objects/LaborExchangeCommunity_FieldProperties__mdt/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <inlineHelpText>API Name for the Field.</inlineHelpText>
    <label>Active</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
                <default>true</default>
                <label>Yes</label>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/LaborExchangeCommunity_FieldProperties__mdt/fields/Custom_Help_Text__c.field-meta.xml
<CustomField>
    <fullName>Custom_Help_Text__c</fullName>
    <inlineHelpText>Help Text for the Field.</inlineHelpText>
    <label>Custom Help Text</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/LaborExchangeCommunity_FieldProperties__mdt/fields/Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Field_API_Name__c</fullName>
    <inlineHelpText>API Name for the Field.</inlineHelpText>
    <label>Field API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LaborExchangeCommunity_FieldProperties__mdt/fields/Field_Label__c.field-meta.xml
<CustomField>
    <fullName>Field_Label__c</fullName>
    <inlineHelpText>Controls the field label should be displayed as within the Community.</inlineHelpText>
    <label>Field Label</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/LaborExchangeCommunity_FieldProperties__mdt/fields/Field_Screen_Size__c.field-meta.xml
<CustomField>
    <fullName>Field_Screen_Size__c</fullName>
    <inlineHelpText>Controls the number of fields displayed per line. There are 12 “spaces” per line. If you want one field in a line, set the screen size to 12. Two fields = 6, Three fields = 4, and 4 fields = 3.</inlineHelpText>
    <label>Field Screen Size</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>2</fullName>
                <default>true</default>
                <label>2</label>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/LaborExchangeCommunity_FieldProperties__mdt/fields/LaborExchangeCommunity_PageProperties__c.field-meta.xml
<CustomField>
    <fullName>LaborExchangeCommunity_PageProperties__c</fullName>
    <inlineHelpText>Controls which Custom Metadata Property Page the Field Properties should be applied to.</inlineHelpText>
    <label>LaborExchangeCommunity_PageProperties</label>
    <referenceTo>LaborExchangeCommunity_PageProperties__mdt</referenceTo>
    <relationshipLabel>LaborExchangeCommunity_FieldProperties</relationshipLabel>
    <relationshipName>LaborExchangeCommunity_FieldProperties</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/LaborExchangeCommunity_FieldProperties__mdt/fields/Override_Setup_Help_Text__c.field-meta.xml
<CustomField>
    <fullName>Override_Setup_Help_Text__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>This allows clients the ability to override the field’s existing help text information only for job seeker community. If left unchecked, it will default to whatever help text is set up for the field across the org,</inlineHelpText>
    <label>Override Setup Help Text</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/LaborExchangeCommunity_FieldProperties__mdt/fields/Read_Only__c.field-meta.xml
<CustomField>
    <fullName>Read_Only__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Controls if the field is informational only.</inlineHelpText>
    <label>Read Only</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/LaborExchangeCommunity_PageProperties__mdt/LaborExchangeCommunity_PageProperties__mdt.object-meta.xml
<CustomObject>
    <label>LaborExchangeCommunity_PageProperties</label>
    <pluralLabel>LaborExchangeCommunity_PageProperties</pluralLabel>
</CustomObject>

force-app/main/default/objects/LaborExchangeCommunity_PageProperties__mdt/fields/Field_Set__c.field-meta.xml
<CustomField>
    <fullName>Field_Set__c</fullName>
    <inlineHelpText>Controls the Field Set that defines the Fields that will display and whether or not they are required.</inlineHelpText>
    <label>Field Set</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LaborExchangeCommunity_PageProperties__mdt/fields/Page__c.field-meta.xml
<CustomField>
    <fullName>Page__c</fullName>
    <inlineHelpText>Controls the Page that this record supports</inlineHelpText>
    <label>Page/Tab/Object Details</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Company Profile</fullName>
            </value>
            <value>
                <fullName>Company Profile &gt; Contact List</fullName>
            </value>
            <value>
                <fullName>Company Profile &gt; Edit/New Contact Popup</fullName>
            </value>
            <value>
                <fullName>Candidate Applications</fullName>
            </value>
            <value>
                <fullName>Job Tile</fullName>
            </value>
            <value>
                <fullName>Job Details</fullName>
            </value>
            <value>
                <fullName>Job Edit</fullName>
            </value>
            <value>
                <fullName>Candidate Detail</fullName>
            </value>
            <value>
                <fullName>Candidate Tile</fullName>
            </value>
            <value>
                <fullName>My Hires</fullName>
            </value>
            <value>
                <fullName>Matches to My Jobs</fullName>
            </value>
            <value>
                <fullName>Event Details</fullName>
            </value>
            <value>
                <fullName>Event Tile</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/LaborExchangeCommunity_PageProperties__mdt/fields/Section_Order__c.field-meta.xml
<CustomField>
    <fullName>Section_Order__c</fullName>
    <inlineHelpText>Controls the Order the Section should appear.</inlineHelpText>
    <label>Section Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LaborExchangeCommunity_PageProperties__mdt/fields/Sub_Header__c.field-meta.xml
<CustomField>
    <fullName>Sub_Header__c</fullName>
    <inlineHelpText>Controls the Text that is displayed in the Sub Header for the Section.</inlineHelpText>
    <label>Sub Header</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/LEXCommunityHelper.cls
public inherited sharing class LEXCommunityHelper {
	/***************************************************
	 * @DESCRIPTION : GETS PICKLIST VALUES FOR A FIELD *
	 * @AUTHOR RADIANHUB DEVELOPER | 04/07/2023        *
	 * @RETURN List<Option>                            *
	 ***************************************************/
	public static List<Option> getPicklistValues(Schema.DescribeFieldResult fieldResult) {
		List<Option> values = new List<Option>();
		for (Schema.PicklistEntry f : fieldResult.getPicklistValues()) {
			values.add(new Option(f.getLabel(), f.getValue()));
		}
		return values;
	}

	/*******************************************************************************
	 * @DESCRIPTION : GETS A LIST OF LEX PAGE PROPERTY METADATA VALUES FOR A FIELD *
	 * @AUTHOR RADIANHUB DEVELOPER | 04/07/2023                                    *
	 * @RETURN List<LaborExchangeCommunity_PageProperties__mdt>                    *
	 *******************************************************************************/
	public static List<LaborExchangeCommunity_PageProperties__mdt> getLEXPageProperties(String page) {
		if (!SObjectHelper.canQueryObj('LaborExchangeCommunity_PageProperties__mdt')) {
			throw SObjectHelperException.queryPermissionException('LaborExchangeCommunity_PageProperties__mdt');
		}
		List<LaborExchangeCommunity_PageProperties__mdt> pp = [
			SELECT Id, Field_Set__c, Section_Header__c, Sub_Header__c, Section_Order__c
			FROM LaborExchangeCommunity_PageProperties__mdt
			WHERE Active__c = 'Yes' AND Page__c = :page
			WITH SECURITY_ENFORCED
			ORDER BY Section_Order__c ASC
		];
		return pp;
	}

	/********************************************************************************
	 * @DESCRIPTION : GETS A LIST OF LEX FIELD PROPERTY METADATA VALUES FOR A FIELD *
	 * @AUTHOR RADIANHUB DEVELOPER | 04/07/2023                                     *
	 * @RETURN List<LaborExchangeCommunity_FieldProperties__mdt>                    *
	 ********************************************************************************/
	public static List<LaborExchangeCommunity_FieldProperties__mdt> getLEXFieldProperties(Set<Id> pagePropertyIds) {
		if (!SObjectHelper.canQueryObj('LaborExchangeCommunity_FieldProperties__mdt')) {
			throw SObjectHelperException.queryPermissionException('LaborExchangeCommunity_FieldProperties__mdt');
		}
		List<LaborExchangeCommunity_FieldProperties__mdt> fp = [
			SELECT
				LaborExchangeCommunity_PageProperties__c,
				Custom_Help_Text__c,
				Field_Api_Name__c,
				Field_Label__c,
				Field_Screen_Size__c,
				Override_Setup_Help_Text__c,
				Read_Only__c
			FROM LaborExchangeCommunity_FieldProperties__mdt
			WHERE Active__c = 'Yes' AND LaborExchangeCommunity_PageProperties__c IN :pagePropertyIds
			WITH SECURITY_ENFORCED
		];
		return fp;
	}

	public static List<FieldWrapper> getFieldsByObjectAndFieldSet(String objectName, String fieldSetName) {
		List<FieldWrapper> fieldWrapperList = new List<FieldWrapper>();

		Schema.FieldSet fieldSet = getFieldSet(objectName, fieldSetName);

		if (fieldSet == null) {
			return fieldWrapperList;
		}

		for (Schema.FieldSetMember fmo : fieldSet.getFields()) {
			fieldWrapperList.add(new FieldWrapper(fmo.getFieldPath(), fmo.getLabel(), String.valueOf(fmo.getType()), fmo.getRequired()));
		}

		return fieldWrapperList;
	}

	public static Schema.FieldSet getFieldSet(String objectName, String fieldSetName) {
		//Map<String, Schema.SObjectType> globalDescribeMap = Schema.getGlobalDescribe();
		//Schema.SObjectType sObjectTypeObj = globalDescribeMap.get(ObjectName);
		Schema.DescribeSObjectResult describeSObjectResultObj = SObjectHelper.getDescribeSObjectResult(objectName);
		//sObjectTypeObj.getDescribe();

		Schema.FieldSet fieldSet = describeSObjectResultObj.FieldSets.getMap().get(fieldSetName);
		// Schema.FieldSet fieldSet = describeSObjectResultObj.FieldSets.getMap().get('LaunchpadCo__Field_Set_1__c');

		// LaunchpadCo__Field_Set_1__c
		// Field_Set_1__c
		if (fieldSet == null && fieldSetName.countMatches('__') == 1) {
			// if () {
			Integer index = fieldSetName.indexOf('__') + 2;
			fieldSetName = fieldSetName.right(fieldSetName.length() - index);
			// } else {
			// field = name;
			// }

			// fieldSetName = 'Field_Set_1__c';
			// describeSObjectResultObj.FieldSets.getMap().get('Field_Set_1__c');

			fieldSet = describeSObjectResultObj.FieldSets.getMap().get(fieldSetName);
		}

		if (fieldSet == null) {
			System.debug('field set not found. Make sure the namespace and field set api name are correct');
		}
		return fieldSet;
	}

	public static List<Option> fetchPicklistValues(Schema.DescribeFieldResult fieldResult) {
		List<Option> values = new List<Option>();
		for (Schema.PicklistEntry f : fieldResult.getPicklistValues()) {
			values.add(new Option(f.getLabel(), f.getValue()));
		}
		return values;
	}

	public static Schema.DescribeSObjectResult getSObjSchema(String sObj) {
		Map<String, Schema.SObjectType> globalDescribeMap = Schema.getGlobalDescribe();
		Schema.SObjectType sObjectTypeObj = globalDescribeMap.get(sObj);
		return sObjectTypeObj.getDescribe();
	}

	public class FieldWrapper {
		@AuraEnabled
		public String fieldApiName;
		@AuraEnabled
		public String fieldLabel;
		@AuraEnabled
		public String fieldType;
		@AuraEnabled
		public Boolean required;

		public FieldWrapper(String fieldApiName, String fieldLabel, String fieldType, Boolean required) {
			this.fieldApiName = fieldApiName;
			this.fieldLabel = fieldLabel;
			this.fieldType = fieldType;
			this.required = required;
		}
	}

	public class Option {
		@AuraEnabled
		public String label;

		@AuraEnabled
		public String value;

		public Option(String label, String value) {
			this.label = label;
			this.value = value;
		}
	}
}