force-app/main/default/objects/LaborExchangeCommunity_HomePage__mdt/LaborExchangeCommunity_HomePage__mdt.object-meta.xml
<CustomObject>
    <label>LaborExchangeCommunity_HomePage</label>
    <pluralLabel>LaborExchangeCommunity_HomePage</pluralLabel>
</CustomObject>

force-app/main/default/objects/LaborExchangeCommunity_HomePage__mdt/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <inlineHelpText>Controls whether or not the Tile should be displayed on the Home Page.</inlineHelpText>
    <label>Active</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
                <default>true</default>
                <label>Yes</label>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/LaborExchangeCommunity_HomePage__mdt/fields/Details__c.field-meta.xml
<CustomField>
    <fullName>Details__c</fullName>
    <inlineHelpText>Controls the Text that is displayed under the Header within the image.</inlineHelpText>
    <label>Details</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/LaborExchangeCommunity_HomePage__mdt/fields/Header__c.field-meta.xml
<CustomField>
    <fullName>Header__c</fullName>
    <inlineHelpText>Controls the text displayed in the Header within the image.</inlineHelpText>
    <label>Header</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/LaborExchangeCommunity_HomePage__mdt/fields/Image_Link__c.field-meta.xml
<CustomField>
    <fullName>Image_Link__c</fullName>
    <label>Image Link</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/LaborExchangeCommunity_HomePage__mdt/fields/Image_URL__c.field-meta.xml
<CustomField>
    <fullName>Image_URL__c</fullName>
    <inlineHelpText>Controls the URL to where the image is stored in Documents</inlineHelpText>
    <label>Image URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/LaborExchangeCommunity_HomePage__mdt/fields/Open_in_New_Tab__c.field-meta.xml
<CustomField>
    <fullName>Open_in_New_Tab__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Controls whether or not a new Tab should be opened when the Tile is clicked.  We recommend using this option for external websites.</inlineHelpText>
    <label>Open in New Tab</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/LaborExchangeCommunity_HomePage__mdt/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <inlineHelpText>Controls the Order the Tile should display in the Row.</inlineHelpText>
    <label>Order</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <default>true</default>
                <label>1</label>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/LaborExchangeCommunity_HomePage__mdt/fields/Redirect_URL__c.field-meta.xml
<CustomField>
    <fullName>Redirect_URL__c</fullName>
    <inlineHelpText>Controls the URL the Participant is redirected to when the Tile is clicked.  This will redirect the Participant to another Tab in the Community or an external website.</inlineHelpText>
    <label>Redirect URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/LaborExchangeCommunity_HomePage__mdt/fields/Row__c.field-meta.xml
<CustomField>
    <fullName>Row__c</fullName>
    <inlineHelpText>Controls the Row that the Tile should be displayed in.</inlineHelpText>
    <label>Row #</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <default>true</default>
                <label>1</label>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/LEXHomePageController.cls
public with sharing class LEXHomePageController {
	@AuraEnabled(cacheable=true)
	public static List<LaborExchangeCommunity_HomePage__mdt> getHomePageTileInfo() {
		return [
			SELECT
				Id,
				Active__c,
				Details__c,
				DeveloperName,
				Header__c,
				Image_URL__c,
				Image_Link__c,
				Label,
				Language,
				MasterLabel,
				Order__c,
				QualifiedApiName,
				Redirect_URL__c,
				Row__c,
				Open_in_New_Tab__c
			FROM LaborExchangeCommunity_HomePage__mdt
			WHERE Active__c = 'Yes'
			WITH SECURITY_ENFORCED
			ORDER BY Row__c ASC, Order__c ASC
		];
	}
}